#!/bin/bash --login

# PBS job options (name, compute nodes, job time)
# PBS -N is the job name (e.g. Example_OMP_Job)
#PBS -N Mandelbrot
# PBS -l select is the number of nodes requested (e.g. 1 node=24 cores)
#PBS -l select=1
# PBS -l walltime, maximum walltime allowed (e.g. 12 hours)
#PBS -l walltime=0:30:0

# Replace [budget code] below with your project code (e.g. t01)
#PBS -A y14

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)               

# Change to the direcotry that the job was submitted from
# (remember this should be on the /work filesystem)
cd $PBS_O_WORKDIR

# Set the number of threads to 12
export OMP_NUM_THREADS=4

# Launch the parallel job
#   Using 1 processes and 12 OpenMP threads
aprun -n 1 -d 4 ./area > my_stdout.txt 2> my_stderr.txt
